import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Box, TextField, Button, Typography, Container } from "@mui/material";

const Register = () => {
  const navigate = useNavigate();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const registerUser = async (username, password) => {
    try {
      const response = await fetch("https://newsletter-ai-backend.vercel.app/api/register/", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username, password }),
      });
  
      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || "Registration failed");
      }
  
      const data = await response.json();
      return data; // Return the success response
    } catch (error) {
      console.error("Error:", error.message);
      return { success: false, error: error.message };
    }
  };
  
  const handleRegister = async (e) => {
    e.preventDefault();
  
    if (password !== confirmPassword) {
      alert("Passwords do not match!");
      return;
    }
  
    console.log("Name:", name);
    console.log("Email:", email);
    console.log("Password:", password);
  
    // Call registerUser and handle the response
    const result = await registerUser(email, password);
  
    if (result.success) {
      alert("Registration successful! Please log in.");
      navigate("/login");
    } else {
      alert(`Registration failed: ${result.error}`);
    }
  };  

  return (
    <Container maxWidth="sm" sx={{ marginTop: 4 }}>
      <Box sx={{ textAlign: "center", marginBottom: 4 }}>
        <Typography variant="h4" sx={{ fontWeight: "bold", marginBottom: 2 }}>
          Register
        </Typography>
        <Typography variant="body1" sx={{ marginBottom: 4 }}>
          Create an account to get started with Newsletter Generated By AI.
        </Typography>

        <form onSubmit={handleRegister}>
          <TextField
            fullWidth
            label="Name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            required
            sx={{ marginBottom: 2 }}
          />
          <TextField
            fullWidth
            label="Email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            type="email"
            required
            sx={{ marginBottom: 2 }}
          />
          <TextField
            fullWidth
            label="Password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            type="password"
            required
            sx={{ marginBottom: 2 }}
          />
          <TextField
            fullWidth
            label="Confirm Password"
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
            type="password"
            required
            sx={{ marginBottom: 4 }}
          />
          <Button
            type="submit"
            variant="contained"
            color="primary"
            fullWidth
            sx={{ paddingY: 1.5, fontWeight: "bold" }}
          >
            Register
          </Button>
        </form>

        {/* Link to Login page */}
        <Box sx={{ marginTop: 2 }}>
          <Typography variant="body2">
            Already have an account?{" "}
            <Button
              onClick={() => navigate("/login")}
              sx={{ fontWeight: "bold", textTransform: "none" }}
            >
              Login Here
            </Button>
          </Typography>
        </Box>
      </Box>
    </Container>
  );
};

export default Register;
